name: CI Guardrails - Branch Policy
description: Enforces branch policies in CI workflows.
author: YourCompany
branding:
  icon: play
  color: blue
inputs:
  message:
    description: Optional message to print
    required: false
    default: Hello from CI Guardrails - Branch Policy
runs:
  using: node20
  main: dist/index.js
